# Generated by Django 3.0.4 on 2020-03-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('webpage', models.URLField()),
                ('pic_url', models.URLField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('actual_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=1024)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('difficulty', models.SmallIntegerField()),
                ('content_quality', models.SmallIntegerField()),
                ('grading', models.SmallIntegerField()),
                ('attendance', models.SmallIntegerField()),
                ('overall_rating', models.SmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Courses')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Profs')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Dept'),
        ),
    ]
