# Generated by Django 3.0.4 on 2020-03-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_auto_20200320_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profs',
            name='pic_url',
        ),
    ]
