# Generated by Django 3.0.4 on 2020-03-21 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0010_remove_profs_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='actual_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='isAnonymous',
            field=models.BooleanField(default=False, verbose_name='Remain Anonymous?'),
        ),
    ]
