# Generated by Django 3.0.4 on 2020-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0011_auto_20200321_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
