# Generated by Django 3.0.4 on 2020-03-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0015_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='banned',
            name='permanent_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banned',
            name='ban_duration',
            field=models.DurationField(null=True),
        ),
    ]
